### PR TITLE
Add event reward manager contract and tests

### PR DESCRIPTION
**Pull request by psychemist**
This is a draft PR that adds a contract for transferring token rewards to the event contract.

This implementation requires two wallet interactions from the event manager to:
1. Create event reward
2. Fund event manager contract with reward tokens

Further changes:
- Combine setup and transfer reward functions
- Add function for updating event reward amount
- Update test scripts to reflect changes

Test cases pass for the current implementation as shown below:

Screenshot 2024-12-14 at 00 41 20
Screenshot 2024-12-14 at 00 41 31

PR will be ready for review after the next commit and push.

### CODE REVIEW

**Comment by Ugo-X** [comment]
> This is a draft PR that adds a contract for transferring token rewards to the event contract.
> 
> This implementation requires two wallet interactions from the event manager to:
> 
> 1. Create event reward
> 2. Fund event manager contract with reward tokens
> 
> Further changes:
> 
> * Combine setup and transfer reward functions
> * Add function for updating event reward amount
> * Update test scripts to reflect changes
> 
> Test cases pass for the current implementation as shown below:
> 
> Screenshot 2024-12-14 at 00 41 20 Screenshot 2024-12-14 at 00 41 31
> PR will be ready for review after the next commit and push.

You are on the right track, please let me know when it's ready for full review and merge

**Comment by psychemist** [comment]
@Ugo-X will do!

**Comment by Ugo-X** [comment]
still not ready for merge?

**Comment by Ugo-X** [comment]
@psychemist I will be reassigning in 6 hours If there is no update from you.

**Comment by psychemist** [comment]
@Ugo-X pushing final changes ASAP

**Comment by Ugo-X** [comment]
> @Ugo-X pushing final changes ASAP

Are you done now?

**Comment by psychemist** [comment]
# Pull Request Overview
Added token transfer logic function logic to transfer tokens to the contract if the event reward type is token-based.

## 📝 Summary
Added an event reward manager contract that allows event managers to create token-based event rewards (USDC or WLD) tokens. There is extra funcitonality for upating event rewards. A full test suite was also included to ensure proper performance.

### Related Issues
- Closes #8

### Type of Change
Mark with an `x` all the checkboxes that apply (like `[x]`).
- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## 🔄 Changes Made
### What's Changed
- Combined setup and transfer reward functions into a `createTokenReward` function
- Added a dedicated function for updating event reward amount
- Updated test scripts to reflect changes

### Implementation Details
- All contracts are compatible with Solidity versions ^0.8.20.
- Project was scaffolded and tested using Foundry

### Technical Notes
There are interactions between the EventManager and EventRewardManager contracts to ensure all events can be validated before performing read and write stateful operations.

## 🔧 Tests Results
Includes testing for invalid amount, indufficient balance, and unauthorized senders.

### Test Coverage
- [x] Unit Tests
- [ ] Integration Tests
- [ ] Manual Testing

### Evidence
Screenshot 2024-12-18 at 10 55 59
Screenshot 2024-12-18 at 10 55 42



### Testing Notes
All test cases passing successfully.

## 🔜 Next Steps
Maintainers review file changes and give edits where necessary.

**Comment by psychemist** [comment]
# Pull Request Overview
Added token transfer logic function logic to transfer tokens to the contract if the event reward type is token-based.

## 📝 Summary
Added an event reward manager contract that allows event managers to create token-based event rewards (USDC or WLD) tokens. There is extra funcitonality for upating event rewards. A full test suite was also included to ensure proper performance.

### Related Issues
- Closes #8

### Type of Change
Mark with an `x` all the checkboxes that apply (like `[x]`).
- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## 🔄 Changes Made
### What's Changed
- Combined setup and transfer reward functions into a `createTokenReward` function
- Added a dedicated function for updating event reward amount
- Updated test scripts to reflect changes

### Implementation Details
- All contracts are compatible with Solidity versions ^0.8.20.
- Project was scaffolded and tested using Foundry

### Technical Notes
There are interactions between the EventManager and EventRewardManager contracts to ensure all events can be validated before performing read and write stateful operations.

## 🔧 Tests Results
Includes testing for invalid amount, insufficient balance, and unauthorized senders.

### Test Coverage
- [x] Unit Tests
- [ ] Integration Tests
- [ ] Manual Testing

### Evidence
Screenshot 2024-12-18 at 10 55 59
Screenshot 2024-12-18 at 10 55 42


### Testing Notes
All 11 test cases pass successfully.

## 🔜 Next Steps
Maintainers review file changes and give edits where necessary.

**Comment by psychemist** [comment]
@Ugo-X ready for review

**Comment by Ugo-X** [comment]
Please make sure the last thing you do is run forge fmt

**Comment by Ugo-X** [comment]
Will review in a bit

**Comment by Ugo-X** [comment]
image

**Comment by psychemist** [comment]
@Ugo-X `forge f mt` has been run. Also updated my test suite to reflect the new `createEvent` funciton logic proposed by other contributors

**Review by Ugo-X — CHANGES_REQUESTED** [review]
1, On token reward creation, create token reward function, should be updated to accept the percentage of the rewards that the the event creator wants to assign for each user
2, change the distribute token reward, to be a claim reward function, whereby the users can claim that reward and that reward should be claimable only if that user is verified in the merkle Tree, same as the nft contract. The nft contract uses the merkle tree to verify if the user is part of the participants

**Comment by psychemist** [comment]
Noted. Will effect changes and get back to you.

**Comment by psychemist** [comment]
working on a fix.are the percentages varied per user or the same for all users?

**Review by Ugo-X — APPROVED** [review]

**Pull request merged**
