### PR TITLE
feat: setup and test

### PR DESCRIPTION
**Pull request by emarc99**
Resolves issues #1 

- [x] Set up the project with the required dependencies for smart contract development and testing.
- [x] Create a skeleton for the event contract with constructor fields worldID address, reward contract address, appId, and actionId.
- [x] Write unit tests for the base event construction.

### CODE REVIEW

**Comment by Ugo-X** [comment]
Please run forge fmt and push again

**Review by Ugo-X — CHANGES_REQUESTED** [review]
Screenshot 2024-12-15 at 07 44 50


please check the function

**Comment by emarc99** [comment]
Applied, sir.

**Review by Ugo-X — CHANGES_REQUESTED** [review]
please resolve conflicts

**Pull request closed without merging**
