### PR TITLE
Withdraw Functionality - FIXES: https://github.com/Explore-Beyond-Innovations/ZeroCheck_Contracts/issues/10

### PR DESCRIPTION
**Pull request by Levi-Ojukwu**
## How I Fixed The Issue

- Modified the struct, adding `createdAt` and `isCanclled` to the structure.
- Defined a constant variable of the wait time required before the unclaimed reward withdrawal operation. 
- Added events for the `TokenRewardWithdrawn` and `TokenRewardCancelled`.
- I created and implemented the `withdrawUnclaimedRewards` function.
- I created and implemented the `cancelAndReclaimReward` function.
- Wrote the unit testing for the functions

### CODE REVIEW

**Review by Ugo-X — CHANGES_REQUESTED** [review]
This is good, well done.  A few changes and we are ready for merge
1 remove the last function, Just the withdrawunclaimedrewards function is okay
2 We'll need to update the token reward struct to keep track of the amount of tokens that have been claimed

**Comment by Levi-Ojukwu** [comment]
Alright, should I remove the test cases for the `cancelAndClaimReward()` function as well, or just the function in the smart contract?

**Review by Ugo-X — APPROVED** [review]
Awesome Work, thank you.

**Review by Ugo-X — CHANGES_REQUESTED** [review]
Screenshot 2024-12-23 at 08 49 24


Forge tests failing?

**Comment by Ugo-X** [comment]
Screenshot 2024-12-23 at 11 20 22

**Review by Ugo-X — APPROVED** [review]

**Pull request merged**
