### PR TITLE
Add createEvent Function and tests for createEvent and event validati…

### PR DESCRIPTION
**Pull request by web3normad**
I created the createEvent function and wrote unit test for each parts.

### CODE REVIEW

**Comment by Ugo-X** [comment]
please run forge fmt

**Comment by web3normad** [comment]
Okay

**Comment by web3normad** [comment]
should I raise a PR again?

**Comment by Ugo-X** [comment]
> should I raise a PR again?

once you run forge fmt, just push

**Comment by web3normad** [comment]
Done

**Review by Ugo-X — CHANGES_REQUESTED** [review]
Screenshot 2024-12-15 at 07 44 50

please check the function

**Comment by web3normad** [comment]
Okay

**Comment by Ugo-X** [comment]
> Function Done

Screenshot 2024-12-15 at 13 42 20

**Comment by Ugo-X** [comment]
please run forge fmt and push again

**Comment by web3normad** [comment]
Done

**Comment by Ugo-X** [comment]
Awesome work, thank you, glad to have you contribute.

**Comment by web3normad** [comment]
Thank you for the opportunity. I’m glad to have contributed to the project.

**Pull request merged**
